AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'Rakefile'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/application.rb'
    - 'bin/*'
    - 'config/'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  UseCache: false
  TargetRailsVersion: 5.1
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario']
Documentation:
  Enabled: false
SymbolArray:
  Enabled: false
